// Code generated by protoc-gen-go. DO NOT EDIT.
// Copied from github.com/BillShiyaoZhang/agent-comm and adapted for platform use.
// source: proto/envelope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EncryptedEnvelope — wire format for agent-comm messages.
// End-to-end encrypted payload only readable by recipient.
type EncryptedEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderUrn          string `protobuf:"bytes,1,opt,name=sender_urn,json=senderUrn,proto3" json:"sender_urn,omitempty"`
	SenderStaticPubkey []byte `protobuf:"bytes,2,opt,name=sender_static_pubkey,json=senderStaticPubkey,proto3" json:"sender_static_pubkey,omitempty"`
	EphemeralPubkey    []byte `protobuf:"bytes,3,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"`
	Nonce              []byte `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext         []byte `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Tag                []byte `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	MessageId          string `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
}

func (x *EncryptedEnvelope) Reset()         { *x = EncryptedEnvelope{} }
func (x *EncryptedEnvelope) String() string  { return protoimpl.X.MessageStringOf(x) }
func (*EncryptedEnvelope) ProtoMessage()     {}

func (x *EncryptedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*EncryptedEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedEnvelope) GetSenderUrn() string {
	if x != nil {
		return x.SenderUrn
	}
	return ""
}
func (x *EncryptedEnvelope) GetSenderStaticPubkey() []byte {
	if x != nil {
		return x.SenderStaticPubkey
	}
	return nil
}
func (x *EncryptedEnvelope) GetEphemeralPubkey() []byte {
	if x != nil {
		return x.EphemeralPubkey
	}
	return nil
}
func (x *EncryptedEnvelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}
func (x *EncryptedEnvelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}
func (x *EncryptedEnvelope) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}
func (x *EncryptedEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_proto_envelope_proto protoreflect.FileDescriptor

var file_proto_envelope_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01,
	0x0a, 0x11, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x72,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55,
	0x72, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x63, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x12, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x50, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61,
	0x6c, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f,
	0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x75, 0x73, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_envelope_proto_rawDescOnce sync.Once
	file_proto_envelope_proto_rawDescData = file_proto_envelope_proto_rawDesc
)

func file_proto_envelope_proto_rawDescGZIP() []byte {
	file_proto_envelope_proto_rawDescOnce.Do(func() {
		file_proto_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_envelope_proto_rawDescData)
	})
	return file_proto_envelope_proto_rawDescData
}

var file_proto_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_envelope_proto_goTypes = []interface{}{
	(*EncryptedEnvelope)(nil),
}
var file_proto_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_envelope_proto_init() }
func file_proto_envelope_proto_init() {
	if File_proto_envelope_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_envelope_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_envelope_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_envelope_proto_goTypes,
		DependencyIndexes: file_proto_envelope_proto_depIdxs,
		MessageInfos:      file_proto_envelope_proto_msgTypes,
	}.Build()
	File_proto_envelope_proto = out.File
	file_proto_envelope_proto_rawDesc = nil
	file_proto_envelope_proto_goTypes = nil
	file_proto_envelope_proto_depIdxs = nil
}
